//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumo1.servicioElGuille {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://elGuille/WebServices", ConfigurationName="servicioElGuille.ConversorSoap")]
    public interface ConversorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://elGuille/WebServices/FaC", ReplyAction="*")]
        double FaC(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://elGuille/WebServices/CaF", ReplyAction="*")]
        double CaF(double valor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConversorSoapChannel : consumo1.servicioElGuille.ConversorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConversorSoapClient : System.ServiceModel.ClientBase<consumo1.servicioElGuille.ConversorSoap>, consumo1.servicioElGuille.ConversorSoap {
        
        public ConversorSoapClient() {
        }
        
        public ConversorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConversorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double FaC(double valor) {
            return base.Channel.FaC(valor);
        }
        
        public double CaF(double valor) {
            return base.Channel.CaF(valor);
        }
    }
}
