//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcEjemploDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ejemplosEntities1 : DbContext
    {
        public ejemplosEntities1()
            : base("name=ejemplosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<clientes> clientes { get; set; }
    
        public virtual int actClientes(Nullable<int> id, string nombre, string apePaterno, string apeMaterno, Nullable<int> edad)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apePaternoParameter = apePaterno != null ?
                new ObjectParameter("apePaterno", apePaterno) :
                new ObjectParameter("apePaterno", typeof(string));
    
            var apeMaternoParameter = apeMaterno != null ?
                new ObjectParameter("apeMaterno", apeMaterno) :
                new ObjectParameter("apeMaterno", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("edad", edad) :
                new ObjectParameter("edad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actClientes", idParameter, nombreParameter, apePaternoParameter, apeMaternoParameter, edadParameter);
        }
    
        public virtual ObjectResult<busClientes_Result> busClientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<busClientes_Result>("busClientes");
        }
    
        public virtual ObjectResult<busIdClientes_Result> busIdClientes(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<busIdClientes_Result>("busIdClientes", iDParameter);
        }
    
        public virtual int guaClientes(string nombre, string apePaterno, string apeMaterno, Nullable<int> edad)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apePaternoParameter = apePaterno != null ?
                new ObjectParameter("apePaterno", apePaterno) :
                new ObjectParameter("apePaterno", typeof(string));
    
            var apeMaternoParameter = apeMaterno != null ?
                new ObjectParameter("apeMaterno", apeMaterno) :
                new ObjectParameter("apeMaterno", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("edad", edad) :
                new ObjectParameter("edad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("guaClientes", nombreParameter, apePaternoParameter, apeMaternoParameter, edadParameter);
        }
    }
}
