//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumoWCF1.servicioWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="deportista", Namespace="http://schemas.datacontract.org/2004/07/wcfClase2")]
    [System.SerializableAttribute()]
    public partial class deportista : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apeMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apePaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int edadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apeMaterno {
            get {
                return this.apeMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apeMaternoField, value) != true)) {
                    this.apeMaternoField = value;
                    this.RaisePropertyChanged("apeMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apePaterno {
            get {
                return this.apePaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apePaternoField, value) != true)) {
                    this.apePaternoField = value;
                    this.RaisePropertyChanged("apePaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                if ((this.edadField.Equals(value) != true)) {
                    this.edadField = value;
                    this.RaisePropertyChanged("edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estatus {
            get {
                return this.estatusField;
            }
            set {
                if ((this.estatusField.Equals(value) != true)) {
                    this.estatusField = value;
                    this.RaisePropertyChanged("estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nivel {
            get {
                return this.nivelField;
            }
            set {
                if ((object.ReferenceEquals(this.nivelField, value) != true)) {
                    this.nivelField = value;
                    this.RaisePropertyChanged("nivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="servicioWCF.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/guardarDeportista", ReplyAction="http://tempuri.org/IService1/guardarDeportistaResponse")]
        bool guardarDeportista(consumoWCF1.servicioWCF.deportista deportista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/guardarDeportista", ReplyAction="http://tempuri.org/IService1/guardarDeportistaResponse")]
        System.Threading.Tasks.Task<bool> guardarDeportistaAsync(consumoWCF1.servicioWCF.deportista deportista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/seleccionarDeportistas", ReplyAction="http://tempuri.org/IService1/seleccionarDeportistasResponse")]
        System.Data.DataSet seleccionarDeportistas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/seleccionarDeportistas", ReplyAction="http://tempuri.org/IService1/seleccionarDeportistasResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> seleccionarDeportistasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deportistaID", ReplyAction="http://tempuri.org/IService1/deportistaIDResponse")]
        System.Data.DataSet deportistaID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deportistaID", ReplyAction="http://tempuri.org/IService1/deportistaIDResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> deportistaIDAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : consumoWCF1.servicioWCF.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<consumoWCF1.servicioWCF.IService1>, consumoWCF1.servicioWCF.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public bool guardarDeportista(consumoWCF1.servicioWCF.deportista deportista) {
            return base.Channel.guardarDeportista(deportista);
        }
        
        public System.Threading.Tasks.Task<bool> guardarDeportistaAsync(consumoWCF1.servicioWCF.deportista deportista) {
            return base.Channel.guardarDeportistaAsync(deportista);
        }
        
        public System.Data.DataSet seleccionarDeportistas() {
            return base.Channel.seleccionarDeportistas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> seleccionarDeportistasAsync() {
            return base.Channel.seleccionarDeportistasAsync();
        }
        
        public System.Data.DataSet deportistaID(int id) {
            return base.Channel.deportistaID(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> deportistaIDAsync(int id) {
            return base.Channel.deportistaIDAsync(id);
        }
    }
}
