//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace invocacionWSVB.WSVB {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSVB.servicioVBSoap")]
    public interface servicioVBSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saludo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string saludo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saludo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> saludoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaGuardar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deportistaGuardar(string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaGuardar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deportistaGuardarAsync(string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaEliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deportistaEliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaEliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deportistaEliminarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaBuscarID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet deportistaBuscarID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaBuscarID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> deportistaBuscarIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaBuscarTodos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet deportistaBuscarTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaBuscarTodos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> deportistaBuscarTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaVerificar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deportistaVerificar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaVerificar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deportistaVerificarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaActualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deportistaActualizar(int id, string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaActualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deportistaActualizarAsync(int id, string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface servicioVBSoapChannel : invocacionWSVB.WSVB.servicioVBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class servicioVBSoapClient : System.ServiceModel.ClientBase<invocacionWSVB.WSVB.servicioVBSoap>, invocacionWSVB.WSVB.servicioVBSoap {
        
        public servicioVBSoapClient() {
        }
        
        public servicioVBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public servicioVBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicioVBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicioVBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string saludo() {
            return base.Channel.saludo();
        }
        
        public System.Threading.Tasks.Task<string> saludoAsync() {
            return base.Channel.saludoAsync();
        }
        
        public bool deportistaGuardar(string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel) {
            return base.Channel.deportistaGuardar(nombre, apePaterno, apeMaterno, edad, estatus, nivel);
        }
        
        public System.Threading.Tasks.Task<bool> deportistaGuardarAsync(string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel) {
            return base.Channel.deportistaGuardarAsync(nombre, apePaterno, apeMaterno, edad, estatus, nivel);
        }
        
        public bool deportistaEliminar(int id) {
            return base.Channel.deportistaEliminar(id);
        }
        
        public System.Threading.Tasks.Task<bool> deportistaEliminarAsync(int id) {
            return base.Channel.deportistaEliminarAsync(id);
        }
        
        public System.Data.DataSet deportistaBuscarID(int id) {
            return base.Channel.deportistaBuscarID(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> deportistaBuscarIDAsync(int id) {
            return base.Channel.deportistaBuscarIDAsync(id);
        }
        
        public System.Data.DataSet deportistaBuscarTodos() {
            return base.Channel.deportistaBuscarTodos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> deportistaBuscarTodosAsync() {
            return base.Channel.deportistaBuscarTodosAsync();
        }
        
        public bool deportistaVerificar(int id) {
            return base.Channel.deportistaVerificar(id);
        }
        
        public System.Threading.Tasks.Task<bool> deportistaVerificarAsync(int id) {
            return base.Channel.deportistaVerificarAsync(id);
        }
        
        public bool deportistaActualizar(int id, string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel) {
            return base.Channel.deportistaActualizar(id, nombre, apePaterno, apeMaterno, edad, estatus, nivel);
        }
        
        public System.Threading.Tasks.Task<bool> deportistaActualizarAsync(int id, string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel) {
            return base.Channel.deportistaActualizarAsync(id, nombre, apePaterno, apeMaterno, edad, estatus, nivel);
        }
    }
}
