'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace WSVC
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSVC.servicioVCSoap")>  _
    Public Interface servicioVCSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function HelloWorld() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deportistaGuardarSP", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function deportistaGuardarSP(ByVal nombre As String, ByVal apePaterno As String, ByVal apeMaterno As String, ByVal edad As Integer, ByVal estatus As Boolean, ByVal nivel As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deportistaGuardarSP", ReplyAction:="*")>  _
        Function deportistaGuardarSPAsync(ByVal nombre As String, ByVal apePaterno As String, ByVal apeMaterno As String, ByVal edad As Integer, ByVal estatus As Boolean, ByVal nivel As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deportistaActualizarSP", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function deportistaActualizarSP(ByVal id As Integer, ByVal nombre As String, ByVal apePaterno As String, ByVal apeMaterno As String, ByVal edad As Integer, ByVal estatus As Boolean, ByVal nivel As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deportistaActualizarSP", ReplyAction:="*")>  _
        Function deportistaActualizarSPAsync(ByVal id As Integer, ByVal nombre As String, ByVal apePaterno As String, ByVal apeMaterno As String, ByVal edad As Integer, ByVal estatus As Boolean, ByVal nivel As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deportistaEliminarSP", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function deportistaEliminarSP(ByVal id As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deportistaEliminarSP", ReplyAction:="*")>  _
        Function deportistaEliminarSPAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deprtistaBuscarTodosSP", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function deprtistaBuscarTodosSP() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deprtistaBuscarTodosSP", ReplyAction:="*")>  _
        Function deprtistaBuscarTodosSPAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deportistaBuscarIDSP", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function deportistaBuscarIDSP(ByVal id As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deportistaBuscarIDSP", ReplyAction:="*")>  _
        Function deportistaBuscarIDSPAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface servicioVCSoapChannel
        Inherits WSVC.servicioVCSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class servicioVCSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSVC.servicioVCSoap)
        Implements WSVC.servicioVCSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function HelloWorld() As String Implements WSVC.servicioVCSoap.HelloWorld
            Return MyBase.Channel.HelloWorld
        End Function
        
        Public Function HelloWorldAsync() As System.Threading.Tasks.Task(Of String) Implements WSVC.servicioVCSoap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync
        End Function
        
        Public Function deportistaGuardarSP(ByVal nombre As String, ByVal apePaterno As String, ByVal apeMaterno As String, ByVal edad As Integer, ByVal estatus As Boolean, ByVal nivel As String) As Boolean Implements WSVC.servicioVCSoap.deportistaGuardarSP
            Return MyBase.Channel.deportistaGuardarSP(nombre, apePaterno, apeMaterno, edad, estatus, nivel)
        End Function
        
        Public Function deportistaGuardarSPAsync(ByVal nombre As String, ByVal apePaterno As String, ByVal apeMaterno As String, ByVal edad As Integer, ByVal estatus As Boolean, ByVal nivel As String) As System.Threading.Tasks.Task(Of Boolean) Implements WSVC.servicioVCSoap.deportistaGuardarSPAsync
            Return MyBase.Channel.deportistaGuardarSPAsync(nombre, apePaterno, apeMaterno, edad, estatus, nivel)
        End Function
        
        Public Function deportistaActualizarSP(ByVal id As Integer, ByVal nombre As String, ByVal apePaterno As String, ByVal apeMaterno As String, ByVal edad As Integer, ByVal estatus As Boolean, ByVal nivel As String) As Boolean Implements WSVC.servicioVCSoap.deportistaActualizarSP
            Return MyBase.Channel.deportistaActualizarSP(id, nombre, apePaterno, apeMaterno, edad, estatus, nivel)
        End Function
        
        Public Function deportistaActualizarSPAsync(ByVal id As Integer, ByVal nombre As String, ByVal apePaterno As String, ByVal apeMaterno As String, ByVal edad As Integer, ByVal estatus As Boolean, ByVal nivel As String) As System.Threading.Tasks.Task(Of Boolean) Implements WSVC.servicioVCSoap.deportistaActualizarSPAsync
            Return MyBase.Channel.deportistaActualizarSPAsync(id, nombre, apePaterno, apeMaterno, edad, estatus, nivel)
        End Function
        
        Public Function deportistaEliminarSP(ByVal id As Integer) As Boolean Implements WSVC.servicioVCSoap.deportistaEliminarSP
            Return MyBase.Channel.deportistaEliminarSP(id)
        End Function
        
        Public Function deportistaEliminarSPAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements WSVC.servicioVCSoap.deportistaEliminarSPAsync
            Return MyBase.Channel.deportistaEliminarSPAsync(id)
        End Function
        
        Public Function deprtistaBuscarTodosSP() As System.Data.DataSet Implements WSVC.servicioVCSoap.deprtistaBuscarTodosSP
            Return MyBase.Channel.deprtistaBuscarTodosSP
        End Function
        
        Public Function deprtistaBuscarTodosSPAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements WSVC.servicioVCSoap.deprtistaBuscarTodosSPAsync
            Return MyBase.Channel.deprtistaBuscarTodosSPAsync
        End Function
        
        Public Function deportistaBuscarIDSP(ByVal id As Integer) As System.Data.DataSet Implements WSVC.servicioVCSoap.deportistaBuscarIDSP
            Return MyBase.Channel.deportistaBuscarIDSP(id)
        End Function
        
        Public Function deportistaBuscarIDSPAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements WSVC.servicioVCSoap.deportistaBuscarIDSPAsync
            Return MyBase.Channel.deportistaBuscarIDSPAsync(id)
        End Function
    End Class
End Namespace
