//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi1
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrito
    {
        public carrito()
        {
            this.consecutivoCarritoes = new HashSet<consecutivoCarrito>();
            this.pedidos = new HashSet<pedido>();
        }
    
        public int id { get; set; }
        public int idProducto { get; set; }
        public int cantidad { get; set; }
        public string descripcion { get; set; }
        public double precio { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual ICollection<consecutivoCarrito> consecutivoCarritoes { get; set; }
        public virtual ICollection<pedido> pedidos { get; set; }
    }
}
