//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi1
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public categoria()
        {
            this.productos = new HashSet<producto>();
        }
    
        public int idCategoria { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public byte[] imagen { get; set; }
    
        public virtual ICollection<producto> productos { get; set; }
    }
}
