//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi1
{
    using System;
    using System.Collections.Generic;
    
    public partial class colonia
    {
        public colonia()
        {
            this.clientes = new HashSet<cliente>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public int cp { get; set; }
        public int idEstado { get; set; }
        public int idCiudad { get; set; }
    
        public virtual ciudade ciudade { get; set; }
        public virtual ICollection<cliente> clientes { get; set; }
    }
}
