//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi1
{
    using System;
    using System.Collections.Generic;
    
    public partial class consecutivoPedido
    {
        public int id { get; set; }
        public int idPedido { get; set; }
        public int idProducto { get; set; }
        public double cantidad { get; set; }
        public double precio { get; set; }
    
        public virtual pedido pedido { get; set; }
        public virtual producto producto { get; set; }
    }
}
