//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi1
{
    using System;
    using System.Collections.Generic;
    
    public partial class consecutivoCarrito
    {
        public int id { get; set; }
        public int idCarrito { get; set; }
        public int idProducto { get; set; }
        public int cantidad { get; set; }
        public int precio { get; set; }
    
        public virtual carrito carrito { get; set; }
    }
}
