//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi1
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado
    {
        public estado()
        {
            this.ciudades = new HashSet<ciudade>();
        }
    
        public int idEstado { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<ciudade> ciudades { get; set; }
    }
}
