//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi1
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public pedido()
        {
            this.consecutivoPedidoes = new HashSet<consecutivoPedido>();
        }
    
        public int idPedido { get; set; }
        public int idCliente { get; set; }
        public int idCarrito { get; set; }
        public string tipoVenta { get; set; }
        public string destino { get; set; }
        public System.DateTime fecha { get; set; }
        public string estatus { get; set; }
        public string recibidoMatriz { get; set; }
        public bool facturar { get; set; }
        public double total { get; set; }
    
        public virtual carrito carrito { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual ICollection<consecutivoPedido> consecutivoPedidoes { get; set; }
    }
}
