//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi1
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.carritoes = new HashSet<carrito>();
            this.consecutivoPedidoes = new HashSet<consecutivoPedido>();
        }
    
        public int idProducto { get; set; }
        public int idCategoria { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public byte[] imagen { get; set; }
        public double costoProduccion { get; set; }
        public double precio1 { get; set; }
        public double precio2 { get; set; }
        public double precio3 { get; set; }
        public double precio4 { get; set; }
        public string unidadMedida { get; set; }
        public double existencia { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public string estatus { get; set; }
        public string observaciones { get; set; }
    
        public virtual ICollection<carrito> carritoes { get; set; }
        public virtual categoria categoria { get; set; }
        public virtual ICollection<consecutivoPedido> consecutivoPedidoes { get; set; }
    }
}
