//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumo1.s2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.disciplina.org/", ConfigurationName="s2.servicioVCSoap")]
    public interface servicioVCSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.disciplina.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.disciplina.org/nombreMetodo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool nombreMetodo(string parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.disciplina.org/deportistaGuardarSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deportistaGuardarSP(string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.disciplina.org/deportistaActualizarSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deportistaActualizarSP(int id, string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.disciplina.org/deportistaEliminarSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deportistaEliminarSP(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.disciplina.org/deprtistaBuscarTodosSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet deprtistaBuscarTodosSP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.disciplina.org/deportistaBuscarIDSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet deportistaBuscarIDSP(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface servicioVCSoapChannel : consumo1.s2.servicioVCSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class servicioVCSoapClient : System.ServiceModel.ClientBase<consumo1.s2.servicioVCSoap>, consumo1.s2.servicioVCSoap {
        
        public servicioVCSoapClient() {
        }
        
        public servicioVCSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public servicioVCSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicioVCSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicioVCSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public bool nombreMetodo(string parametros) {
            return base.Channel.nombreMetodo(parametros);
        }
        
        public bool deportistaGuardarSP(string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel) {
            return base.Channel.deportistaGuardarSP(nombre, apePaterno, apeMaterno, edad, estatus, nivel);
        }
        
        public bool deportistaActualizarSP(int id, string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel) {
            return base.Channel.deportistaActualizarSP(id, nombre, apePaterno, apeMaterno, edad, estatus, nivel);
        }
        
        public bool deportistaEliminarSP(int id) {
            return base.Channel.deportistaEliminarSP(id);
        }
        
        public System.Data.DataSet deprtistaBuscarTodosSP() {
            return base.Channel.deprtistaBuscarTodosSP();
        }
        
        public System.Data.DataSet deportistaBuscarIDSP(int id) {
            return base.Channel.deportistaBuscarIDSP(id);
        }
    }
}
