//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcf1
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    /// <summary>using System.Runtime.Serialization;
    /// esto es despues de agregar el modelo, se tiene que agregar la referencia
    /// de uso de using System.Runtime.Serialization;
    /// </summary>
    [DataContract]
    public partial class deportista
    {
        [DataMember]
        public int id { get; set; }
        [DataMember]
        public string nombre { get; set; }
        [DataMember]
        public string apePaterno { get; set; }
        [DataMember]
        public string apeMaterno { get; set; }
        [DataMember]
        public int edad { get; set; }
        [DataMember]
        public bool estatus { get; set; }
        [DataMember]
        public string nivel { get; set; }
    }
}
