//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfClase2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class programacionpwEntities : DbContext
    {
        public programacionpwEntities()
            : base("name=programacionpwEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<deportista> deportistas { get; set; }
    
        public virtual ObjectResult<spBusDep_Result> spBusDep()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBusDep_Result>("spBusDep");
        }
    
        public virtual ObjectResult<spBusDepID_Result> spBusDepID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBusDepID_Result>("spBusDepID", idParameter);
        }
    
        public virtual int spDepAct(Nullable<int> id, string nombre, string apePaterno, string apeMaterno, Nullable<int> edad, Nullable<bool> estatus, string nivel)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apePaternoParameter = apePaterno != null ?
                new ObjectParameter("apePaterno", apePaterno) :
                new ObjectParameter("apePaterno", typeof(string));
    
            var apeMaternoParameter = apeMaterno != null ?
                new ObjectParameter("apeMaterno", apeMaterno) :
                new ObjectParameter("apeMaterno", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("edad", edad) :
                new ObjectParameter("edad", typeof(int));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("estatus", estatus) :
                new ObjectParameter("estatus", typeof(bool));
    
            var nivelParameter = nivel != null ?
                new ObjectParameter("nivel", nivel) :
                new ObjectParameter("nivel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDepAct", idParameter, nombreParameter, apePaternoParameter, apeMaternoParameter, edadParameter, estatusParameter, nivelParameter);
        }
    
        public virtual int spDepGuardar(string nombre, string apePaterno, string apeMaterno, Nullable<int> edad, Nullable<bool> estatus, string nivel)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apePaternoParameter = apePaterno != null ?
                new ObjectParameter("apePaterno", apePaterno) :
                new ObjectParameter("apePaterno", typeof(string));
    
            var apeMaternoParameter = apeMaterno != null ?
                new ObjectParameter("apeMaterno", apeMaterno) :
                new ObjectParameter("apeMaterno", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("edad", edad) :
                new ObjectParameter("edad", typeof(int));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("estatus", estatus) :
                new ObjectParameter("estatus", typeof(bool));
    
            var nivelParameter = nivel != null ?
                new ObjectParameter("nivel", nivel) :
                new ObjectParameter("nivel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDepGuardar", nombreParameter, apePaternoParameter, apeMaternoParameter, edadParameter, estatusParameter, nivelParameter);
        }
    
        public virtual int spEliDepID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliDepID", idParameter);
        }
    }
}
