//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace invocacionWSVB.WSVBSP {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSVBSP.servicioVBSPSoap")]
    public interface servicioVBSPSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaGuardarSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deportistaGuardarSP(string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaGuardarSP", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deportistaGuardarSPAsync(string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaBuscarTodosSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet deportistaBuscarTodosSP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaBuscarTodosSP", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> deportistaBuscarTodosSPAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaBuscarIDSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet deportistaBuscarIDSP(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaBuscarIDSP", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> deportistaBuscarIDSPAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaActualizarSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deportistaActualizarSP(int id, string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaActualizarSP", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deportistaActualizarSPAsync(int id, string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaEliminarSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deportistaEliminarSP(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deportistaEliminarSP", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deportistaEliminarSPAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface servicioVBSPSoapChannel : invocacionWSVB.WSVBSP.servicioVBSPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class servicioVBSPSoapClient : System.ServiceModel.ClientBase<invocacionWSVB.WSVBSP.servicioVBSPSoap>, invocacionWSVB.WSVBSP.servicioVBSPSoap {
        
        public servicioVBSPSoapClient() {
        }
        
        public servicioVBSPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public servicioVBSPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicioVBSPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicioVBSPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public bool deportistaGuardarSP(string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel) {
            return base.Channel.deportistaGuardarSP(nombre, apePaterno, apeMaterno, edad, estatus, nivel);
        }
        
        public System.Threading.Tasks.Task<bool> deportistaGuardarSPAsync(string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel) {
            return base.Channel.deportistaGuardarSPAsync(nombre, apePaterno, apeMaterno, edad, estatus, nivel);
        }
        
        public System.Data.DataSet deportistaBuscarTodosSP() {
            return base.Channel.deportistaBuscarTodosSP();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> deportistaBuscarTodosSPAsync() {
            return base.Channel.deportistaBuscarTodosSPAsync();
        }
        
        public System.Data.DataSet deportistaBuscarIDSP(int id) {
            return base.Channel.deportistaBuscarIDSP(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> deportistaBuscarIDSPAsync(int id) {
            return base.Channel.deportistaBuscarIDSPAsync(id);
        }
        
        public bool deportistaActualizarSP(int id, string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel) {
            return base.Channel.deportistaActualizarSP(id, nombre, apePaterno, apeMaterno, edad, estatus, nivel);
        }
        
        public System.Threading.Tasks.Task<bool> deportistaActualizarSPAsync(int id, string nombre, string apePaterno, string apeMaterno, int edad, bool estatus, string nivel) {
            return base.Channel.deportistaActualizarSPAsync(id, nombre, apePaterno, apeMaterno, edad, estatus, nivel);
        }
        
        public bool deportistaEliminarSP(int id) {
            return base.Channel.deportistaEliminarSP(id);
        }
        
        public System.Threading.Tasks.Task<bool> deportistaEliminarSPAsync(int id) {
            return base.Channel.deportistaEliminarSPAsync(id);
        }
    }
}
